import {
  DarkTheme as PaperDarkTheme,
  DefaultTheme as PaperDefaultTheme,
} from 'react-native-paper';
import {
  DefaultTheme as NavigationDefaultTheme,
  DarkTheme as NavigationDarkTheme,
} from '@react-navigation/native';
const LIGHT_COLOR = {
  PURPLE_700: '#E18B00',
  PURPLE_600: '#410A9A',
  PURPLE_100: '#FBF7FD',
  BLACK_24: '#242424',
  BLUE_600: '#DFEDFD',
  BLUE_300: '#DFEDFD',
  BLUE_200: '#E7EAFD',
  BLUE_100: '#F6F7FE',
  BLACK_900: '#182135',
  GRAY_700: '#595959',
  GRAY_600: '#8E8E8E',
  GRAY_100: '#F7F7F7',
  GRAY_400: '#E3E3E3',
  GRAY_300: '#707070',
  GRAY_500: '#CDCDCD',
  WHITE90: '#F9F9F9',
  WHITE: '#FFF',
  BACKDROP: '#18213599',
  TEXTINPUT_BG: '#EDEDED',
  KAKAOTALK: '#FEE500',
  FACEBOOK: '#1877F2',
  TRANSPARENT: 'transparent',
  BACKGROUND_LOGIN: '#CFC6E2',
  BLACK: '#000',
  PLACE_HOLDER: '#CFCFCF',
  ORANGE: '#F06B1A',
  VIOLET_LIGHT: '#E7D9FD',
  GRAY: '#F5F5F5',
  TEXT_CONTENT: '#1E1E1E',
  TEXT_CONTENT_GRAY: '#686868',
  TAB_GRAY: '#828282',
  LAYOUT: 'rgba(0, 0, 0, 0.3)',
  RGB_BLACK_LIGHT: 'rgba(0, 0, 0, 0.52)',
  BLUE: '#00A3E1',
  BLUE50: '#5173F3',
  SPLASH: '#FFF',
  GREEN: '#1FCFC1',
  GREEN_100: '#3AB19D',
  GREEN_BLAND: '#F4FDFF',
  RED: '#F52929',
  PINK: '#FE7991',
  PINK_S: '#FF6161',
  PINK_LIGHT: '#FFCAD4',
  YELLOW: '#EFC75E',
  BORDER_GRAY: '#BFBFBF',
  ORANGE_LV_MAX: '#FF7E4B',
  HINT: '#686868',
  INPUT: '#A4C4CB',
  BACKGROUND_CONTENT: '#E8E8E8',
  BACKGROUND_TABAR: '#FFEFEF',
  HARMONIES: '#3AB19D',
  RED_LIGHT: '#FF6161',
  GRAY_200: '#939393',
  BTN_BLACK: '#1E1E1E',
  BORDER_INPUT_GRAY: '#C1C1C1',
  GRAY_800: '#4A5461',
  GOLD_DROP_ORANGE: '#E18B00',
  ORANGE_VISIBLE: '#FFEFEF',
  ORANGE_LIGHT: '#C6A300',
  GRAY_900: '#E7E7E7',
  GRAY_D9: '#D9D9D9',
};
const DARK_COLOR = {
  PURPLE_700: '#000',
  PURPLE_600: '#410A9A',
  PURPLE_100: '#FBF7FD',
  BLUE_600: '#DFEDFD',
  BLUE_300: '#DFEDFD',
  BLUE_200: '#E7EAFD',
  BLUE_100: '#F6F7FE',
  BLACK_900: '#182135',
  GRAY_700: '#595959',
  GRAY_600: '#8E8E8E',
  GRAY_500: '#CDCDCD',
  GRAY_100: '#F7F7F7',
  WHITE: '#FFF',
  GRAY_400: '#E3E3E3',
  GRAY_300: '#707070',
  BACKDROP: '#18213599',
  TEXTINPUT_BG: '#EDEDED',
  KAKAOTALK: '#FEE500',
  FACEBOOK: '#1877F2',
  TRANSPARENT: 'transparent',
  BACKGROUND_LOGIN: '#CFC6E2',
  BLACK: '#000',
  PLACE_HOLDER: '#CFCFCF',
  ORANGE: '#F06B1A',
  VIOLET_LIGHT: '#E7D9FD',
  GRAY: '#D2D2D2',
  TEXT_CONTENT: '#1E1E1E',
  TEXT_CONTENT_GRAY: '#686868',
  TAB_GRAY: '#828282',

  LAYOUT: 'rgba(0, 0, 0, 0.3)',
  RGB_BLACK_LIGHT: 'rgba(0, 0, 0, 0.5)',
  BLUE: '#00A3E1',
  SPLASH: '#FFF',
  GREEN: '#1FCFC1',
  RED: '#F52929',
  PINK: '#FE7991',
  PINK_LIGHT: '#FFCAD4',
  YELLOW: '#EFC75E',
  BORDER_GRAY: '#BFBFBF',
  ORANGE_LV_MAX: '#FF7E4B',
  HARMONIES: '#3AB19D',
  RED_LIGHT: '#FF6161',
  GRAY_200: '#939393',
  BTN_BLACK: '#1E1E1E',
  BORDER_INPUT_GRAY: '#C1C1C1',
  BORDER_BOTTOM_GRAY: '#939393',
  GRAY_800: '#4A5461',
  GOLD_DROP_ORANGE: '#E18B00',
  ORANGE_VISIBLE: '#FFEFEF',
  ORANGE_LIGHT: '#C6A300',
  GRAY_900: '#E7E7E7',
  GRAY_D9: '#D9D9D9',
};
export const PaperThemeDefault = {
  ...PaperDefaultTheme,
  roundness: 12,
  colors: {
    ...PaperDefaultTheme.colors,
    ...NavigationDefaultTheme.colors,
    primary: LIGHT_COLOR.PURPLE_700,
    accent: LIGHT_COLOR.BLUE_600,
    shadow: LIGHT_COLOR.GRAY_600,
    text: LIGHT_COLOR.TEXT_CONTENT_GRAY,
    background: LIGHT_COLOR.WHITE,
    white: LIGHT_COLOR.WHITE,
    white90: LIGHT_COLOR.WHITE90,
    purple_600: LIGHT_COLOR.PURPLE_600,
    purple_100: LIGHT_COLOR.PURPLE_100,
    gray_400: LIGHT_COLOR.GRAY_400,
    gray_500: LIGHT_COLOR.GRAY_500,
    gray_700: LIGHT_COLOR.GRAY_700,
    gray_100: LIGHT_COLOR.GRAY_100,
    blue_300: LIGHT_COLOR.BLUE_300,
    blue_200: LIGHT_COLOR.BLUE_200,
    blue_100: LIGHT_COLOR.BLUE_100,
    backdrop: LIGHT_COLOR.BACKDROP,
    textinput_bg: LIGHT_COLOR.TEXTINPUT_BG,
    kakaotalk: LIGHT_COLOR.KAKAOTALK,
    facebook: LIGHT_COLOR.FACEBOOK,
    transparent: LIGHT_COLOR.TRANSPARENT,
    background_login: LIGHT_COLOR.BACKGROUND_LOGIN,
    black: LIGHT_COLOR.BLACK,
    black_24: LIGHT_COLOR.BLACK_24,
    placeholder: LIGHT_COLOR.PLACE_HOLDER,
    orange: LIGHT_COLOR.ORANGE,
    violet_light: LIGHT_COLOR.VIOLET_LIGHT,
    gray: LIGHT_COLOR.GRAY,
    text_content: LIGHT_COLOR.TEXT_CONTENT,
    text_content_gray: LIGHT_COLOR.TEXT_CONTENT_GRAY,
    tab_gray: LIGHT_COLOR.TAB_GRAY,
    layout: LIGHT_COLOR.LAYOUT,
    gray_300: LIGHT_COLOR.GRAY_300,
    rgb_black_light: LIGHT_COLOR.RGB_BLACK_LIGHT,
    blue: LIGHT_COLOR.BLUE,
    blue50: LIGHT_COLOR.BLUE50,
    splash: LIGHT_COLOR.SPLASH,
    green: LIGHT_COLOR.GREEN,
    green_bland: LIGHT_COLOR.GREEN_BLAND,
    green_100: LIGHT_COLOR.GREEN_100,
    red: LIGHT_COLOR.RED,
    pink: LIGHT_COLOR.PINK,
    pink_s: LIGHT_COLOR.PINK_S,
    pink_light: LIGHT_COLOR.PINK_LIGHT,
    yellow: LIGHT_COLOR.YELLOW,
    border_gray: LIGHT_COLOR.BORDER_GRAY,
    orange_lv_max: LIGHT_COLOR.ORANGE_LV_MAX,
    hint: LIGHT_COLOR.HINT,
    input: LIGHT_COLOR.INPUT,
    backgroundContent: LIGHT_COLOR.BACKGROUND_CONTENT,
    backgroundtabar: LIGHT_COLOR.BACKGROUND_TABAR,
    harmonies: LIGHT_COLOR.HARMONIES,
    red_light: LIGHT_COLOR.RED_LIGHT,
    gray_200: LIGHT_COLOR.GRAY_200,
    btn_black: LIGHT_COLOR.BTN_BLACK,
    border_input_gray: LIGHT_COLOR.BORDER_INPUT_GRAY,
    boder_bottom_gray: LIGHT_COLOR.BORDER_BOTTOM_GRAY,
    gray_800: LIGHT_COLOR.GRAY_800,
    gold_500: LIGHT_COLOR.GOLD_DROP_ORANGE,
    orange_visible: LIGHT_COLOR.ORANGE_VISIBLE,
    orange_light: LIGHT_COLOR.ORANGE_LIGHT,
    gray_900: LIGHT_COLOR.GRAY_900,
    gray_d9: LIGHT_COLOR.GRAY_D9,
  },
};
export const PaperThemeDark = {
  ...PaperDarkTheme,
  roundness: 12,
  colors: {
    ...PaperDarkTheme.colors,
    ...NavigationDarkTheme.colors,
    primary: DARK_COLOR.PURPLE_700,
    accent: DARK_COLOR.BLUE_600,
    shadow: DARK_COLOR.GRAY_600,
    text: DARK_COLOR.WHITE,
    background: DARK_COLOR.BLACK_900,
    gray_400: DARK_COLOR.GRAY_400,
    gray_500: DARK_COLOR.GRAY_500,
    gray_700: DARK_COLOR.GRAY_700,
    gray_100: DARK_COLOR.GRAY_100,
    blue_300: DARK_COLOR.BLUE_300,
    blue_200: DARK_COLOR.BLUE_200,
    blue_100: DARK_COLOR.BLUE_100,
    white: DARK_COLOR.WHITE,
    surface: DARK_COLOR.BLACK_900,
    purple_100: DARK_COLOR.PURPLE_100,
    purple_600: DARK_COLOR.PURPLE_600,
    backdrop: DARK_COLOR.BACKDROP,
    textinput_bg: DARK_COLOR.TEXTINPUT_BG,
    kakaotalk: DARK_COLOR.KAKAOTALK,
    facebook: DARK_COLOR.FACEBOOK,
    transparent: DARK_COLOR.TRANSPARENT,
    background_login: DARK_COLOR.BACKGROUND_LOGIN,
    black: DARK_COLOR.BLACK,
    placeholder: DARK_COLOR.PLACE_HOLDER,
    orange: DARK_COLOR.ORANGE,
    violet_light: DARK_COLOR.VIOLET_LIGHT,
    gray: DARK_COLOR.GRAY,
    text_content: DARK_COLOR.TEXT_CONTENT,
    text_content_gray: DARK_COLOR.TEXT_CONTENT_GRAY,
    tab_gray: DARK_COLOR.TAB_GRAY,
    layout: DARK_COLOR.LAYOUT,
    gray_300: DARK_COLOR.GRAY_300,
    rgb_black_light: DARK_COLOR.RGB_BLACK_LIGHT,
    blue: DARK_COLOR.BLUE,
    splash: DARK_COLOR.SPLASH,
    green: DARK_COLOR.GREEN,
    red: DARK_COLOR.RED,
    pink: DARK_COLOR.PINK,
    pink_light: DARK_COLOR.PINK_LIGHT,
    yellow: DARK_COLOR.YELLOW,
    border_gray: DARK_COLOR.BORDER_GRAY,
    orange_lv_max: DARK_COLOR.ORANGE_LV_MAX,
    pink_s: LIGHT_COLOR.PINK_S,
    harmonies: LIGHT_COLOR.HARMONIES,
    red_light: DARK_COLOR.RED_LIGHT,
    gray_200: DARK_COLOR.GRAY_200,
    btn_black: DARK_COLOR.BTN_BLACK,
    border_input_gray: DARK_COLOR.BORDER_INPUT_GRAY,
    boder_bottom_gray: DARK_COLOR.BORDER_BOTTOM_GRAY,
    gray_800: DARK_COLOR.GRAY_800,
    gold_500: DARK_COLOR.GOLD_DROP_ORANGE,
    orange_visible: LIGHT_COLOR.ORANGE_VISIBLE,
    orange_light: DARK_COLOR.ORANGE_LIGHT,
    gray_900: DARK_COLOR.GRAY_900,
    gray_d9: DARK_COLOR.GRAY_D9,
  },
};
export const CombinedDefaultTheme = {
  ...PaperDefaultTheme,
  ...NavigationDefaultTheme,
};
export const CombinedDarkTheme = {
  ...PaperDarkTheme,
  ...NavigationDarkTheme,
  colors: {
    ...PaperDarkTheme.colors,
    ...NavigationDarkTheme.colors,
  },
};
